name: Build & Test

on:
  push:
    # branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.15
      uses: actions/setup-node@v3
      with:
        node-version: 16.15
        cache: 'npm'
        registry-url: 'https://npm.pkg.github.com'
    - run: npm ci
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: npm run format-check -ws
    - run: npm run build -ws
    - run: npm run lint -ws
    - run: npm test -ws
